### PR TITLE
Add custom annotations category

### PR DESCRIPTION
**Pull request by jonc125**
Create category for https://github.com/ModellingWebLab/WebLab/issues/255

### CODE REVIEW

**Comment by mirams** [comment]
So the idea here is you can tag things with "is a custom label" and the WL will be able to understand the new tag?

**Comment by MichaelClerx** [comment]
So you can't just _not_ use the oxmeta ontology? You still need to say "this is a different ontology" by including a special tag from the oxmeta ontology?

**Comment by jonc125** [comment]
Not quite. This is just providing a category that will appear in the annotation tool. The tool will automatically stick non-oxmeta annotations into this category - neither the model nor protocol will need to mention it.

**Comment by MichaelClerx** [comment]
Should that not live somewhere else then?
To stop this becoming an ontology of "things that exists in cell ephys" + "things that we useful for WL" ?

**Comment by jonc125** [comment]
We already have Chaste/WebLab specific stuff in there, and I think that's OK. Besides, the idea of a custom annotation category seems pretty generic to me - useful as a catch-all for stuff that doesn't fit elsewhere, if nothing else!

**Review by mirams — APPROVED** [review]

**Pull request merged**
