### PR TITLE
Added probability

### PR DESCRIPTION
**Pull request by MauriceHendrix**

### CODE REVIEW

**Comment by MauriceHendrix** [comment]
@mirams can you have a look whether I'm adding probabilitie sin the right place? See teh diff on `oxford-metadata.ttl` (the other file is auto generated)

**Comment by mirams** [comment]
I've pushed some changes to the branch, which appear to have been added to pull request above. I think this is what we would want, in terms of being able to Annotate variables directly as being Gates/States and the ontology knowing this means they are probabilities so chaste_codegen can make suitable methods for `VerifyStateVariables`.

The only thing I am not sure about is what will happen in the WebLab annotation tool if we have something like "fast_sodium_current_m_gate" and also the generic annotation of "hodgkin_huxley_state" available, hopefully this would all play nicely (i.e. the variable could be given either tag with the same effect for `VerifyStateVariables`, but only the one that was dragged and dropped onto it would appear against it in the annotation tool).

**Review by mirams — APPROVED** [review]
If you think this works we can give it a try...!

**Review by mirams — CHANGES_REQUESTED** [review]
forgot, the RDF needs regenerating from this

**Review by mirams — APPROVED** [review]

**Pull request merged**
